const enviroments = { dev: "dev", prod: "prod" };

module.exports = {
  env: enviroments.dev,
  baseApiURL: {
    dev: "http://52.170.189.52:8080",
    prod: "",
  },
  language: "EN",
  apiKey: "de8mTVyN2r8Ixn3sBeT0",
  messageState: [
    { message: "Hello", messageCode: "HL" },
    { message: "Login", messageCode: "CHK01" },
    { message: "Home", messageCode: "CHK02" },
    { message: "Log Out", messageCode: "CHK03" },
    { message: "Select Option", messageCode: "CHK04" },
    { message: "Checkpoint", messageCode: "CHK05" },
    { message: "Daily Data", messageCode: "CHK06" },
    { message: "Scan Angle Location Label", messageCode: "CHK07" },
    { message: "Process", messageCode: "CHK08" },
    { message: "Pass", messageCode: "CHK09" },
    { message: "Fail", messageCode: "CHK10" },
    { message: "Peel Off", messageCode: "CHK11" },
    { message: "Scratched", messageCode: "CHK12" },
    { message: "Missing Key", messageCode: "CHK13" },
    { message: "Missing Screw Post", messageCode: "CHK14" },
    { message: "Damage Screw Post", messageCode: "CHK15" },
    { message: "Missing Hook", messageCode: "CHK16" },
    { message: "Missing Keys Support", messageCode: "CHK17" },
    { message: "Complete", messageCode: "CHK18" },
    { message: "Customer", messageCode: "CHK19" },
    { message: "Model", messageCode: "CHK20" },
    { message: "disassembly", messageCode: "CHK21" },
    { message: "refresh", messageCode: "CHK22" },
    { message: "Date", messageCode: "CHK23" },
    { message: "Back", messageCode: "CHK24" },
    { message: "Next", messageCode: "CHK25" },
    { message: "Select Process", messageCode: "CHK26" },
    { message: "Select Model", messageCode: "CHK27" },
    { message: "Select Customer", messageCode: "CHK28" },
    { message: "Export to", messageCode: "CHK29" },
    { message: "Location", messageCode: "CHK30" },
    { message: "Fails", messageCode: "CHK31" },
    { message: "Failures", messageCode: "CHK32" }]
};
